spring.application.name=demo

# Aiven.io MySQL connection string (Apna actual URL, username, password yahan lagayein)
# Aiven MySQL Connection Settings
spring.datasource.url=jdbc:mysql://mysql-24015be3-dreamswaiting175-7ec4.l.aivencloud.com:15721/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=yAVNS_x1m6wHoV2MzKfUYz4w6
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
 # spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Optional: Connection Pool settings
spring.datasource.hikari.maximum-pool-size=5

# Automatic Table Creation & SQL Logs
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Allow React Frontend to connect without CORS error
spring.mvc.cors.allowed-origins=http://localhost:5173,http://localhost:5174